### ISSUE TITLE
passing answers as argument doesnt work

### ISSUE THREAD

**Issue by dinosath** [aliev/baker#15]
Tried passing answers as arguments in the cli both ways mentioned in the documentation

<img width="1086" alt="Image" src="https://github.com/user-attachments/assets/9b18799d-c076-4e75-ad53-db3459259df6" />

and 

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/82aa3cf0-2b9d-4e0f-aacc-2ac531a3c12e" />

but neither of them worked

**Comment by aliev** [comment]
When `answers` is passed as an argument, it goes into `default` (as shown in your screenshot). If you press Enter, the default value (in your case, `[test]`) will be accepted.

If you want to accept the default `answer` and skip the prompt, you can add an extra condition in your `baker.yaml` using `ask_if`:

```yaml
schemaVersion: v1

questions:
  platform_name:
    type: str
    help: "Please enter a platform name"
    default: "{{platform.os}}"
    ask_if: platform_name is not defined
```

Example:

```bash
> cat example1/README.md.baker.j2
Platform name: {{platform_name}}

> echo '{"platform_name": "OSX"}' | baker example1 out --answers=-
Template generation completed successfully in out.

> cat out/README.md
Platform name: OSX
```

**Comment by dinosath** [comment]
what if i want to run it from ci?

**Comment by aliev** [comment]
> what if i want to run it from ci?

Yes, the solution I provided is exactly what you need for CI environments!

When you add the `ask_if` condition to each question and provide all answers via the `--answers` parameter, Baker will completely skip the interactive prompts and run non-interactively - perfect for CI pipelines.

Here's a complete example showing how to set this up:

```yaml
schemaVersion: v1

questions:
  project_name:
    type: str
    help: Please enter the name of your project
    ask_if: project_name is not defined  # Skip if already provided

  project_author:
    type: str
    help: "Please enter the author's name for {{project_name}}"
    ask_if: project_author is not defined  # Skip if already provided

  project_slug:
    type: str
    help: Please enter the project slug (or press Enter to use the default)
    default: "{{ project_name|lower|replace(' ', '_') }}"
    ask_if: project_slug is not defined  # Skip if already provided

  use_tests:
    type: bool
    help: Will your project include tests?
    default: true
    ask_if: use_tests is not defined  # Skip if already provided
```

In your CI pipeline

```bash
# This will run completely non-interactively with no prompts
baker template output-dir --answers='{"project_name": "test", "project_author": "john", "project_slug": "test", "use_tests": true}'
```

With this setup, Baker will:

1. Check each question to see if its answer already exists in the provided `--answers`
2. Skip prompting completely for questions that have answers
3. Run from start to finish with no user interaction

The `ask_if: X is not defined` pattern is the key - it tells Baker "only ask this question if the answer isn't already provided."
